apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: nextjs
  name: {{ .Release.Name }}-nextjs-deploy
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: nextjs
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nextjs
    spec:
      containers:
      - image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        name: {{ .Values.image.name }}
        resources: {}
status: {}