apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-nextjs-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
  - host: adonisshabani.info
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service: 
            name: {{ .Release.Name }}-nextjs-svc
            port:
              number: {{ .Values.ports.port }}
