apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: nextjs
    app.kubernetes.io/managed-by: Helm
  name: {{ .Release.Name }}-nextjs-svc
spec:
  ports:
  - port: {{ .Values.ports.port }}
    protocol: {{ .Values.ports.protocol }}
    targetPort: {{ .Values.ports.targetPort }}
  selector:
    app: nextjs
status:
  loadBalancer: {}