apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: nextjs
    app.kubernetes.io/managed-by: Helm
  name: {{ .Release.Name }}-nextjs-svc
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: nextjs
status:
  loadBalancer: {}